innovate-technologies/itframe

components/dj/separation.js
Add the separation rules used in DJ. 
These come in 2 flavours: seperating the artist name and just seperating unique songs. Depends on how well the client pays royalties. I mean..... the local authorities want it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/3)
=> [WIP]Add separation rules

components/dj/separation.js, components/maya/support.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/4)
=> Remove Spanish

.eslintrc, .gitignore, components/nowplaying/tunein.js, http/control/tunein-air-integration.js, npm-debug.log, package.json
Added validation of TuneIn details by sending a song update, if it fails it will respond with a 500 error to Control to display the error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/5)
=> Added validation of TuneIn details by sending a song update

components/control/controlUser.js, components/legacy/phpSerialize.js, components/legacy/whmcs.js, http/control/00-security.js, http/control/feedback.js, http/control/info.js, http/internal/apps.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/8)
=> controlUser: Switch to async/await

.travis.yml, README.md
Add travis file to test-compile with babel to get an error if we make a syntax error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/16)
=> Add travis file to test-compile with babel

components/tunes/personalMusicDatabase.js, http/internal/tunes.js
This route is made for a cron-based script that will ask ITFrame if it uses a specific link so it can remove old and unused ones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/17)
=> Add checks for tunes links if they are used

components/cast/database.js, components/cast/manage.js, http/control/cast.js
Add extra Cast features like antiStreamRipper and hideListenerCount. This code is still in wait.for syntax to keep consistency (to be rewritten in a later refactor PR)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/14)
=> Add antiStreamRipper and hideListenerCount

components/cast/configHelper.js
Updates the Cast unit file to run the new image
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/18)
=> Update Cast unit file

components/legacy/whmcs.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/22)
=> WHMCS: Fix wrong response type being requested

http/control/support.js
I wish JS had better static analysis tools to catch things like this…
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/24)
=> Support: Fix broken import

components/tunes/process.js, http/internal/tunes.js
By this we "hack" fleet to only have. 4 jobs at once per machine. More can slow down and potentially DoS the tunes workers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/23)
=> Tunes worker: add random number and conflict it

components/cast/database.js, components/dj/clocks.js, components/dj/intervals.js, components/dj/manage.js, http/control/dj.js, http/dj/clocks.js, http/dj/intervals.js
Adding extra routes needed for the DJ frontend.
*Needs testing*
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/11)
=> Routes needed for DJ

components/cast/database.js, components/cast/stats/calculated.js, components/cast/stats/listeners.js, components/cast/stats/sessions.js, http/cast/config.js, http/cast/stats.js
Add routes for Cast's statistics
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/15)
=> Cast statistics

components/tunes/personalMusicDatabase.js, http/control/tunes.js
add /control/tunes/update-default-artwork/:username to update the default artwork as described in #27
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/29)
=> Add /control/tunes/update-default-artwork/:username

components/cast/configHelper.js, components/cast/manage.js, components/dj/intervals.js, http/control/dj.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/32)
=> Dj improvements

components/auth/timetoken.js, components/auth/timetokenDatabase.js, components/buildinfo/database.js, components/cast/configHelper.js, components/cast/database.js, components/cast/manage.js, components/coreos/fleet.js, components/dj/manage.js, components/iOS/legacy.js, components/player/database.js, http/cast/config.js, http/control/info.js, http/dj/00-security.js, http/internal/apps.js, http/internal/gitlab.js, http/legacy/centova.js, http/legacy/whmcs.js, http/public/buildInfo.js, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/33)
=> Cast refactor

components/cast/configHelper.js, components/cast/manage.js, http/control/cast.js
Adds the option to set a custom domain on Cast.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/39)
=> Add /control/cast/custom-domain/

src/components/cast/manage.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/45)
=> add icecast-yp.internet-radio.com

src/components/tunes/personalMusicDatabase.js, src/http/control/tunes.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/42)
=> redo processedURLS

config.example.json, src/components/dispatch/dispatch.js, src/components/tunes/process.js, src/http/internal/tunes.js
This adds 2 dispatch functions and the process to comminucate to dispatch instead of fleet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/46)
=> rewrite tunes-worker to use dispatch

package-lock.json, src/components/redisClient.js, src/http/control/00-security.js, src/package.json
Since req.user.product is populated on every route that works on a specific account, and WHMCS is pretty slow, let's cache the product info to make things faster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/48)
=> Control: Cache user products

src/components/legacy/whmcs.js, src/http/control/00-security.js
Turns out 00-security isn't the only file that makes us of products and is super slow as a result.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/49)
=> Cache products in the WHMCS code

src/components/dj/intervals.js
This adds the ability to limit intervals to play on certain days and/or time of day
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/52)
=> add more options for intervals

.travis.yml, src/.babelrc, src/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/54)
=> Travis: Fix babel invokation

src/components/coreos/etcd.js
I don't see why an init method is required
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/60)
=> etcd: Init on first use

src/components/coreos/dns.js, src/components/coreos/etcd.js, src/http/legacy/centova.js
We must use await/then, otherwise exec() will never be called for us
automatically
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/itframe/61)
=> etcd: Fix usage of etcd3 lib

src/components/cast/stats/songs.js, src/http/cast/stats.js
=> Cast song history

package.json, src/components/auth/timetoken.js, src/components/auth/tokenDatabase.js, src/http/legacy/centova.js
=> rm time tokens

src/components/dj/intervals.js, src/components/dj/tags.js, src/components/legacy/usersDatabase.js, src/components/nowplaying/tuneinDatabase.js, src/components/nowplaying/twitterDatabase.js
Signed-off-by: Maartje Eyskens <meyskens@me.com>
=> Remove all use of _.extend to update db records

.travis.yml, Dockerfile
Signed-off-by: Maartje Eyskens <meyskens@me.com>
=> Use node.js 10

src/package-lock.json, src/package.json
Reverts innovate-technologies/itframe#432
=> Revert "Bump mongoose from 5.4.16 to 5.5.6 in /src"
